name: Hello JNUer StuHealth

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # gitä»“åº“åˆ°è™šæ‹Ÿæœº
      - name: Update Codes ğŸ””
        uses: actions/checkout@v1
        
      # ç¡®å®šç‰ˆæœ¬ 
      - name: Choose Version ğŸ‘‹
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
          
      # æ›´æ–°è™šæ‹Ÿæœºæ—¶é—´
      - name: Update Time ğŸ“…
        run: tzutil /s "China Standard Time"
        
      # å®‰è£…ä¾èµ–åº“
      - name: Install dependencies ğŸ˜Š
        run: pip3 install -r requirements.txt
        
        
      # æ‰§è¡Œæ‰“å¡æ–‡ä»¶
      - name: Clock In ğŸš€
        run: python3 ./Clock.py -a ${{ secrets.Account }} -p ${{ secrets.Password }}
        
      # å‘é€é‚®ä»¶
      - name: Send Mail ğŸ“§
        run: python3 ./Mail.py -e ${{ secrets.Email }} -c ${{ secrets.Cookie }} -s ${{ secrets.Service }}



