name: Hello JNUer StuHealth

on:
  push:
  schedule:
    - cron: '1 0 * * *'
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      # gitä»“åº“åˆ°è™šæ‹Ÿæœº
      - name: Update Codes ğŸ””
        uses: actions/checkout@v1
        
      # æ›´æ–°è™šæ‹Ÿæœºæ—¶é—´
      - name: Update Time ğŸ“…
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
        
      # å®‰è£…ä¾èµ–åº“
      - name: Install dependencies ğŸ˜Š
        run: pip3 install -r requirements.txt
        
      # æ‰§è¡Œæ‰“å¡æ–‡ä»¶
      - name: Clock In ğŸš€
        run: sudo whereis crypto
      
      # æ›´æ–°æ–‡ä»¶åå­—
      - name: Update folder names ğŸŒŸ
        run: python3 -c "import os; from distutils.sysconfig import get_python_lib; os.rename(str(get_python_lib()) + '/crypto', str(get_python_lib()) + '/Crypto') "
       
      # æ‰§è¡Œæ‰“å¡æ–‡ä»¶
      - name: Clock In ğŸš€
        run: sudo python3 ./Clock.py -a ${{ secrets.Account }} -p ${{ secrets.Password }}
        
      # å‘é€é‚®ä»¶
      - name: Send Mail ğŸ“§
        run: sudo python3 ./Mail.py -e ${{ secrets.Email }} -p ${{ secrets.Cooike }}



