name: Hello JNUer StuHealth

on:
  push:
  schedule:
    - cron: '1 0 * * *'
    
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      # gitä»“åº“åˆ°è™šæ‹Ÿæœº
      - name: Update Codes ğŸ””
        uses: actions/checkout@v1
        
      # ç¡®å®šç‰ˆæœ¬ 
      - name: Choose Version ğŸ‘‹
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
          architecture: x64
          
      # æ›´æ–°è™šæ‹Ÿæœºæ—¶é—´
      - name: Update Time ğŸ“…
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
        
      # å®‰è£…ä¾èµ–åº“
      - name: Install dependencies ğŸ˜Š
        run: pip3 install -r requirements.txt
        
      # æ‰§è¡Œæ‰“å¡æ–‡ä»¶
      - name: Clock In ğŸš€
        run: sudo export LD_LIBRARY_PATH = /opt/hostedtoolcache/Python/3.9.0-beta.4/x64/lib/python3.9/site-packages
       
      # æ‰§è¡Œæ‰“å¡æ–‡ä»¶
      - name: Clock In ğŸš€
        run: sudo python3 ./Clock.py -a ${{ secrets.Account }} -p 1
        
      # å‘é€é‚®ä»¶
      - name: Send Mail ğŸ“§
        run: sudo python3 ./Mail.py -e ${{ secrets.Email }} -p ${{ secrets.Cooike }}



